#!/usr/bin/env bash

# magniFIND-seq K562 production-reproduction profile. Replace only input paths.
PROJECT_NAME="k562_resistance_production"
BULK_MATRIX="/path/to/SPGZKS-expression-matrix.tsv"
BULK_SAMPLE_METADATA="study_bulk_samples.tsv"
BULK_DE_TABLE="/path/to/SPGZKS-Resist_vs_Sensitive-dge.csv"
SEURAT_RDS="/path/to/K562_SR_uncorrected_seurat.rds"
OUT_DIR="../output/k562_resistance_production"

CONDITION_A="K562-R"
CONDITION_B="K562-S"
BULK_COUNT_SUFFIX="_count"
BULK_GENE_ID_COLUMN="gene_id"
BULK_GENE_NAME_COLUMN="gene_name"
BULK_GENE_BIOTYPE_COLUMN="gene_biotype"

# The archived table reports GroupB/GroupA (sensitive/resistant).
BULK_DE_GENE_ID_COLUMN="EnsemblID"
BULK_DE_GENE_NAME_COLUMN="gene_name"
BULK_DE_GENE_BIOTYPE_COLUMN="gene_biotype"
BULK_DE_LOGFC_COLUMN="logFC"
BULK_DE_PVALUE_COLUMN="PValue"
BULK_DE_FDR_COLUMN="FDR"
BULK_DE_LOGFC_MULTIPLIER=-1

SC_ASSAY="RNA"
SC_COUNTS_LAYER="counts"
SC_CONDITION_COLUMN="condition"
SC_FEATURE_COLUMN=""
SC_KEEP_COLUMN=""

FDR_THRESHOLD=0.05
MIN_ABS_LOG2FC=1
TOP_N_PER_DIRECTION=50
SIGNATURE_REQUIRE_BULK_DEG=1
REQUIRE_FULL_SIGNATURE=1
MIN_BULK_REPLICATES_PER_CONDITION=2
SC_MIN_TOTAL_COUNTS=1
SC_CPM_PSEUDOCOUNT=1
SC_DE_TEST="wilcox"
SC_DE_LOGFC_THRESHOLD=0
SC_DE_MIN_PCT=0
EXCLUDE_GENE_REGEX='^MT-|^RP[SL]'
MODULE_SCORE_SEED=20260729
MODULE_SCORE_CTRL=50
MODULE_SCORE_NBIN=24
SKIP_COMPLETED=1
