# Trusted shell configuration for bulk-to-single-cell concordance analysis.

PROJECT_NAME="k562_resistance"
BULK_MATRIX="bulk_expression_matrix.tsv"
BULK_SAMPLE_METADATA="bulk_samples.tsv"
SEURAT_RDS="single_cell.rds"
OUT_DIR="../output/k562_resistance_concordance"

# The reported bulk and single-cell log2 fold change is condition A versus B.
CONDITION_A="K562-R"
CONDITION_B="K562-S"

# Bulk matrix columns are matched as <sample><suffix>. Use an empty suffix when
# the matrix column names exactly equal the sample names in the metadata file.
BULK_COUNT_SUFFIX="_count"
BULK_GENE_ID_COLUMN="gene_id"
BULK_GENE_NAME_COLUMN="gene_name"
BULK_GENE_BIOTYPE_COLUMN="gene_biotype"

# For exact K562 manuscript signature reproduction, provide the archived
# SPGZKS-Resist_vs_Sensitive-dge.csv generated by the production bulk workflow.
# The production table reports GroupB/GroupA, so -1 converts it to K562-R/K562-S.
# Leave empty only when intentionally recomputing differential expression from
# the raw count columns with the repository's pinned edgeR environment.
BULK_DE_TABLE=""
BULK_DE_GENE_ID_COLUMN="EnsemblID"
BULK_DE_GENE_NAME_COLUMN="gene_name"
BULK_DE_GENE_BIOTYPE_COLUMN="gene_biotype"
BULK_DE_LOGFC_COLUMN="logFC"
BULK_DE_PVALUE_COLUMN="PValue"
BULK_DE_FDR_COLUMN="FDR"
BULK_DE_LOGFC_MULTIPLIER=-1

SC_ASSAY="RNA"
SC_COUNTS_LAYER="counts"
SC_CONDITION_COLUMN="condition"

# Leave empty to match bulk gene_name against Seurat feature names. Set this to
# an assay feature-metadata column when Seurat row names are gene IDs.
SC_FEATURE_COLUMN=""

# Optional logical metadata column defining cells eligible for analysis and
# module scoring. A/B cells are used for differential expression; other labels
# (for example PBMC) are retained for resistance-score reporting.
SC_KEEP_COLUMN=""

FDR_THRESHOLD=0.05
MIN_ABS_LOG2FC=1
TOP_N_PER_DIRECTION=50
# Production selection first required FDR < 0.05 and |log2FC| >= 1.
SIGNATURE_REQUIRE_BULK_DEG=1
# Manuscript reproduction must select exactly 50 genes in both directions.
# Set to 0 only for exploratory analyses that deliberately allow shorter sets.
REQUIRE_FULL_SIGNATURE=1
# edgeR dispersion estimation requires biological replication. The study has
# three libraries per condition; two is the minimum accepted default.
MIN_BULK_REPLICATES_PER_CONDITION=2
SC_MIN_TOTAL_COUNTS=1
SC_CPM_PSEUDOCOUNT=1
# Single-cell effect sizes used for concordance are estimated from
# log-normalized counts with Seurat::FindMarkers, matching the manuscript.
SC_DE_TEST="wilcox"
SC_DE_LOGFC_THRESHOLD=0
SC_DE_MIN_PCT=0
EXCLUDE_GENE_REGEX='^MT-|^RP[SL]'

# Bulk-derived resistance score definition used in the K562 analysis:
# condition-A-high AddModuleScore minus condition-B-high AddModuleScore.
MODULE_SCORE_SEED=20260729
MODULE_SCORE_CTRL=50
MODULE_SCORE_NBIN=24

SKIP_COMPLETED=1
